import "dotenv/config";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import Product from "./models/Product.js";
import Category from "./models/Category.js";
import User from "./models/User.js";
const categories = [
  {
    name: "Audio",
    slug: "audio",
    description: "Audio collection",
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    displayOrder: 1,
  },
  {
    name: "Wearables",
    slug: "wearables",
    description: "Wearables collection",
    image:
      "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=900&q=80",
    displayOrder: 2,
  },
  {
    name: "Cameras",
    slug: "cameras",
    description: "Cameras collection",
    image:
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80",
    displayOrder: 3,
  },
  {
    name: "Accessories",
    slug: "accessories",
    description: "Accessories collection",
    image:
      "https://images.unsplash.com/photo-1589872307379-0ffdf9829123?auto=format&fit=crop&w=900&q=80",
    displayOrder: 4,
  },
  {
    name: "Computers",
    slug: "computers",
    description: "Computers collection",
    image:
      "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    displayOrder: 5,
  },
];
const products = [
  {
    name: "Aurora Pro Headphones",
    slug: "aurora-pro-headphones",
    sku: "NC-001",
    description:
      "Premium aurora pro headphones designed for modern everyday use.",
    price: 179,
    compareAtPrice: 211,
    category: "Audio",
    brand: "NovaSound",
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 12,
    rating: 4.4,
    reviewCount: 80,
    tags: ["audio", "novasound"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: true,
    isActive: true,
    soldCount: 100,
  },
  {
    name: "Halo Mini Speaker",
    slug: "halo-mini-speaker",
    sku: "NC-002",
    description: "Premium halo mini speaker designed for modern everyday use.",
    price: 89,
    compareAtPrice: 105,
    category: "Audio",
    brand: "NovaSound",
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 15,
    rating: 4.5,
    reviewCount: 103,
    tags: ["audio", "novasound"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: false,
    isActive: true,
    soldCount: 137,
  },
  {
    name: "Echo Studio Earbuds",
    slug: "echo-studio-earbuds",
    sku: "NC-003",
    description:
      "Premium echo studio earbuds designed for modern everyday use.",
    price: 129,
    compareAtPrice: 152,
    category: "Audio",
    brand: "NovaSound",
    image:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 18,
    rating: 4.6,
    reviewCount: 126,
    tags: ["audio", "novasound"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: false,
    isActive: true,
    soldCount: 174,
  },
  {
    name: "Vinyl Wave Turntable",
    slug: "vinyl-wave-turntable",
    sku: "NC-004",
    description:
      "Premium vinyl wave turntable designed for modern everyday use.",
    price: 249,
    compareAtPrice: 294,
    category: "Audio",
    brand: "Orbit Labs",
    image:
      "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 21,
    rating: 4.7,
    reviewCount: 149,
    tags: ["audio", "orbit labs"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: true,
    isActive: true,
    soldCount: 211,
  },
  {
    name: "Pulse X Smartwatch",
    slug: "pulse-x-smartwatch",
    sku: "NC-005",
    description: "Premium pulse x smartwatch designed for modern everyday use.",
    price: 229,
    compareAtPrice: 270,
    category: "Wearables",
    brand: "Pulse",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 24,
    rating: 4.8,
    reviewCount: 172,
    tags: ["wearables", "pulse"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: false,
    isActive: true,
    soldCount: 248,
  },
  {
    name: "Pulse Fit Band",
    slug: "pulse-fit-band",
    sku: "NC-006",
    description: "Premium pulse fit band designed for modern everyday use.",
    price: 79,
    compareAtPrice: 93,
    category: "Wearables",
    brand: "Pulse",
    image:
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 27,
    rating: 4.4,
    reviewCount: 195,
    tags: ["wearables", "pulse"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: false,
    isActive: true,
    soldCount: 285,
  },
  {
    name: "Air Ring One",
    slug: "air-ring-one",
    sku: "NC-007",
    description: "Premium air ring one designed for modern everyday use.",
    price: 199,
    compareAtPrice: 235,
    category: "Wearables",
    brand: "Aero",
    image:
      "https://tse4.mm.bing.net/th/id/OIP.dqNoVtLLEULycGmIxkdM_wHaGN?r=0&pid=Api&h=220&P=0",
    images: [
      "https://tse4.mm.bing.net/th/id/OIP.dqNoVtLLEULycGmIxkdM_wHaGN?r=0&pid=Api&h=220&P=0",
    ],
    stock: 30,
    rating: 4.5,
    reviewCount: 218,
    tags: ["wearables", "aero"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: true,
    isActive: true,
    soldCount: 322,
  },
  {
    name: "Orbit M50 Camera",
    slug: "orbit-m50-camera",
    sku: "NC-008",
    description: "Premium orbit m50 camera designed for modern everyday use.",
    price: 899,
    compareAtPrice: 1061,
    category: "Cameras",
    brand: "Orbit Labs",
    image:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 33,
    rating: 4.6,
    reviewCount: 241,
    tags: ["cameras", "orbit labs"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: true,
    featured: false,
    isActive: true,
    soldCount: 359,
  },
  {
    name: "Orbit Street Lens 35",
    slug: "orbit-street-lens-35",
    sku: "NC-009",
    description:
      "Premium orbit street lens 35 designed for modern everyday use.",
    price: 449,
    compareAtPrice: 530,
    category: "Cameras",
    brand: "Orbit Labs",
    image:
      "https://images.unsplash.com/photo-1606986628253-8bb3d2e4d3aa?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1606986628253-8bb3d2e4d3aa?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 36,
    rating: 4.7,
    reviewCount: 264,
    tags: ["cameras", "orbit labs"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 396,
  },
  {
    name: "Creator Pocket Camera",
    slug: "creator-pocket-camera",
    sku: "NC-010",
    description:
      "Premium creator pocket camera designed for modern everyday use.",
    price: 349,
    compareAtPrice: 412,
    category: "Cameras",
    brand: "Frame",
    image:
      "https://images.unsplash.com/photo-1589872307379-0ffdf9829123?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1589872307379-0ffdf9829123?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 39,
    rating: 4.8,
    reviewCount: 287,
    tags: ["cameras", "frame"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: true,
    isActive: true,
    soldCount: 433,
  },
  {
    name: "Aero Mechanical Keyboard",
    slug: "aero-mechanical-keyboard",
    sku: "NC-011",
    description:
      "Premium aero mechanical keyboard designed for modern everyday use.",
    price: 139,
    compareAtPrice: 164,
    category: "Accessories",
    brand: "Aero",
    image:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 42,
    rating: 4.4,
    reviewCount: 310,
    tags: ["accessories", "aero"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 470,
  },
  {
    name: "Glide Wireless Mouse",
    slug: "glide-wireless-mouse",
    sku: "NC-012",
    description:
      "Premium glide wireless mouse designed for modern everyday use.",
    price: 69,
    compareAtPrice: 81,
    category: "Accessories",
    brand: "Aero",
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 45,
    rating: 4.5,
    reviewCount: 333,
    tags: ["accessories", "aero"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 507,
  },
  {
    name: "PowerDock 7-in-1",
    slug: "powerdock-7-in-1",
    sku: "NC-013",
    description: "Premium powerdock 7-in-1 designed for modern everyday use.",
    price: 99,
    compareAtPrice: 117,
    category: "Accessories",
    brand: "Volt",
    image:
      "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 48,
    rating: 4.6,
    reviewCount: 356,
    tags: ["accessories", "volt"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: true,
    isActive: true,
    soldCount: 544,
  },
  {
    name: "Arc Desk Lamp",
    slug: "arc-desk-lamp",
    sku: "NC-014",
    description: "Premium arc desk lamp designed for modern everyday use.",
    price: 119,
    compareAtPrice: 140,
    category: "Accessories",
    brand: "Lumen",
    image:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 51,
    rating: 4.7,
    reviewCount: 379,
    tags: ["accessories", "lumen"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 581,
  },
  {
    name: "NovaBook Air 14",
    slug: "novabook-air-14",
    sku: "NC-015",
    description: "Premium novabook air 14 designed for modern everyday use.",
    price: 1199,
    compareAtPrice: 1415,
    category: "Computers",
    brand: "Nova",
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 54,
    rating: 4.8,
    reviewCount: 402,
    tags: ["computers", "nova"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 618,
  },
  {
    name: "NovaBook Pro 16",
    slug: "novabook-pro-16",
    sku: "NC-016",
    description: "Premium novabook pro 16 designed for modern everyday use.",
    price: 1899,
    compareAtPrice: 2241,
    category: "Computers",
    brand: "Nova",
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 57,
    rating: 4.4,
    reviewCount: 425,
    tags: ["computers", "nova"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: true,
    isActive: true,
    soldCount: 655,
  },
  {
    name: "Nova Mini Desktop",
    slug: "nova-mini-desktop",
    sku: "NC-017",
    description: "Premium nova mini desktop designed for modern everyday use.",
    price: 699,
    compareAtPrice: 825,
    category: "Computers",
    brand: "Nova",
    image:
      "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 60,
    rating: 4.5,
    reviewCount: 448,
    tags: ["computers", "nova"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 692,
  },
  {
    name: "Canvas 27 Monitor",
    slug: "canvas-27-monitor",
    sku: "NC-018",
    description: "Premium canvas 27 monitor designed for modern everyday use.",
    price: 499,
    compareAtPrice: 589,
    category: "Computers",
    brand: "Frame",
    image:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    ],
    stock: 63,
    rating: 4.6,
    reviewCount: 471,
    tags: ["computers", "frame"],
    colors: ["Black", "Silver"],
    specifications: { Warranty: "2 years", Shipping: "Free over $150" },
    trending: false,
    featured: false,
    isActive: true,
    soldCount: 729,
  },
];
if (!process.env.MONGODB_URI)
  throw new Error("MONGODB_URI is missing from .env");
await mongoose.connect(process.env.MONGODB_URI);
try {
  await Product.deleteMany({});
  await Category.deleteMany({});
  const created = await Category.insertMany(categories);
  const map = new Map(created.map((c) => [c.name, c._id]));
  await Product.insertMany(
    products.map((p) => ({ ...p, categoryRef: map.get(p.category) })),
  );
  const password = await bcrypt.hash("Admin123!", 12);
  await User.findOneAndUpdate(
    { email: "admin@novacart.dev" },
    {
      name: "Nova Admin",
      email: "admin@novacart.dev",
      password,
      role: "admin",
      isEmailConfirmed: true,
    },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );
  console.log(
    `Seed complete: ${categories.length} categories, ${products.length} products.`,
  );
} finally {
  await mongoose.disconnect();
}
